name: Build and Push

on:
  workflow_dispatch:
    inputs:
      mirror:
        default: 'http://archive.ubuntu.com/ubuntu'
      directory:
        default: 'pool/main/c/casper'
      version:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: nyow/deb-builder:ha
    steps:
      - name: Download source file
        run: wget "${{ github.event.inputs.mirror }}/${{ github.event.inputs.directory }}/casper_${{ github.event.inputs.version }}.tar.xz"
      - name: Extract source file
        run: tar xf ${{ github.event.inputs.filename }}
      - name: Build the package
        env:
          DEBFULLNAME: ${{ vars.DEBFULLNAME }}
          DEBEMAIL: ${{ vars.DEBEMAIL }}
        run: |
          cd casper
          sed -i 's/USERNAME="ubuntu"/USERNAME="nyow"/g' casper.conf
          sed -i 's/HOST="ubuntu"/HOST="nyow"/g' casper.conf
          dch -v ${{ github.event.inputs.version }}nyow --force-distribution -D ha "Reconfigure for Nyow."
          mk-build-deps --install --tool 'apt -y --no-install-recommends' debian/control
          dpkg-buildpackage -us -uc
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4.3.5
        with:
          name: build-artifacts
          path: |
            *.dsc
            *.tar.xz
            *.deb
