name: Build and Push

on:
  workflow_dispatch:
    inputs:
      mirror:
        default: 'http://archive.ubuntu.com/ubuntu'
      directory:
        default: 'pool/main/c/casper'
      version:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: nyow/deb-builder:ha
    env:
      SOURCE_FILENAME: casper_${{ github.event.inputs.version }}.tar.xz
    steps:
      - name: Download source file
        run: wget "${{ github.event.inputs.mirror }}/${{ github.event.inputs.directory }}/$SOURCE_FILENAME"
      - name: Extract source file
        run: tar xf $SOURCE_FILENAME && rm $SOURCE_FILENAME
      - name: Build the package
        env:
          DEBFULLNAME: ${{ vars.DEBFULLNAME }}
          DEBEMAIL: ${{ vars.DEBEMAIL }}
        run: |
          cd casper
          sed -i 's/USERNAME="ubuntu"/USERNAME="nyow"/g' casper.conf
          sed -i 's/HOST="ubuntu"/HOST="nyow"/g' casper.conf
          dch -v ${{ github.event.inputs.version }}nyow --force-distribution -D ha "Reconfigure for Nyow."
          mk-build-deps --install --tool 'apt -y --no-install-recommends' debian/control
          rm -f casper-build-deps*
          dpkg-buildpackage -us -uc
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4.3.5
        with:
          name: build-artifacts
          path: |
            *.dsc
            *.tar.xz
            *.deb

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.event.inputs.version }}
          name: ${{ github.event.inputs.version }}
          body: Release ${{ github.event.inputs.version }}
          artifacts: |
            *.dsc
            *.tar.xz
            *.deb

  push:
    needs: release
    runs-on: ubuntu-latest
    env:
      DIRECTORY_NAME: casper_${{ github.event.inputs.version }}nyow
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: '${{ env.DIRECTORY_NAME }}'
      - name: Compress artifact directory
        run: |
          tar -cJvf $DIRECTORY_NAME.tar.xz -C $DIRECTORY_NAME .
      - name: Push artifact to Nyow archive
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
            username: '${{ secrets.SFTP_USERNAME }}'
            server: '${{ secrets.SFTP_HOST }}'
            ssh_private_key: ${{ secrets.SFTP_PRIVATE_KEY }}
            local_path: './${{ env.DIRECTORY_NAME }}.tar.xz'
            remote_path: '/ha-unstable'
